Game_Sections = {
	'PuzzleFighter': 'CPS2',
	'DanKuGa': 'Taito',
	'LandMaker': 'Taito',
	'NeoBomberman': 'NEOGEO',
	'MagDrop3': 'NEOGEO',
	'MagDrop2': 'NEOGEO',
}

CPS2_unitIDs = {
    'PuzzleFighter_Akuma': '0x96',
    'PuzzleFighter_Anita': '0x97',
    'PuzzleFighter_ChunLi': '0x98',
    'PuzzleFighter_Dan': '0x99',
    'PuzzleFighter_Devilotte': '0x9A',
    'PuzzleFighter_Donovan': '0x9B',
    'PuzzleFighter_Felicia': '0x9C',
    'PuzzleFighter_HsienKo': '0x9D',
    'PuzzleFighter_Ken': '0x9E',
    'PuzzleFighter_LeiLei': '0x9F',
    'PuzzleFighter_Morrigan': '0xA0',
    'PuzzleFighter_Ryu': '0xA1',
    'PuzzleFighter_Sakura': '0xA2',
    'PuzzleFighter_Bonus': '0xA3',
    'PuzzleFighter_Stages': '0xA4',
}
CPS2_IMG_IDs = {
    'Base': '0x00',
    'MonoSprite0': '0x80',
    'MonoSprite1': '0x81',
}

PuzzleFighter_imgIDs = {
    'Base': '0x00',
    'CSI': '0x40',
}

PuzzleFighter_CharSpec_imgIDs = {
    'PuzzleFighter_Akuma': {  # unitID: 0x96
        'Base': '0x00',
        'FireGouHadouken': '0x01',
        'CSI': '0x40',
        'Portrait': '0x41',

    },
    'PuzzleFighter_Anita': {  # unitID: 0x97
        'Base': '0x00',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_ChunLi': {  # unitID: 0x98
        'Base': '0x00',
        'Kikouken': '0x01',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_Dan': {  # unitID: 0x99
        'Base': '0x00',
        'Tears': '0x01',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_Devilotte': {  # unitID: 0x9A
        'Base': '0x00',
        'Dave': '0x01',
        'LaserGun': '0x02',
        'Xavier': '0x03',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_Donovan': {  # unitID: 0x9B
        'Base': '0x00',
        'Anita': '0x01',
        'DhylecBlade': '0x02',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_Felicia': {  # unitID: 0x9C
        'Base': '0x00',
        'Dust': '0x01',
        'SandSplash': '0x02',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_HsienKo': {  # unitID: 0x9D
        'Base': '0x00',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_Ken': {  # unitID: 0x9E
        'Base': '0x00',
        'ShoryukenFlames': '0x01',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_LeiLei': {  # unitID: 0x9F
        'Base': '0x00',
        'Weapons': '0x01',
        'LinLin': '0x02',
        'IntermissionExtra': '0x03',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_Morrigan': {  # unitID: 0xA0
        'Base': '0x00',
        'Sparkles': '0x01',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_Ryu': {  # unitID: 0xA1
        'Base': '0x00',
        'Hadouken': '0x01',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_Sakura': {  # unitID: 0xA2
        'Base': '0x00',
        'Hadouken': '0x01',
        'CSI': '0x40',
        'Portrait': '0x41',
    },
    'PuzzleFighter_Bonus': {  # unitID: 0xA3
        'CharSelectCounterGemStuff': '0x00',
        'WarningDamageIcon': '0x01',
        'CapcomLogo': '0x02',
        'CharacterNames': '0x03',
        'CharacterSelectIcons': '0x04',
        'IntroBackground': '0x05',
        'LevelSelect': '0x06',
        'MetalGems': '0x07',
        'ModeSelect': '0x08',
        'PlayerSelect': '0x09',
        'QSoundScreen': '0x0A',
        'RandomSelectIcon': '0x0B',
        'RecycleScreen': '0x0C',
        'SelectCursor': '0x0D',
        'SelectIconsBackground': '0x0E',
        'SelectPortraitBackground': '0x0F',
        'SelectScreenBackground': '0x10',
        'StageText': '0x11',
        'SuperGems': '0x12',
        'TitleScreen': '0x13',
        'TutorialJoystick&Buttons': '0x14',
        'TutorialPazzleDojo': '0x15',
        'VSScreen': '0x16',
        'VSText': '0x17',
    },
    'PuzzleFighter_Stages': {  # unitID: 0xA4
        'Ryu00': '0x00',
        'Ryu01': '0x01',
        'Ryu02': '0x02',
    },

}

Taito_unitIDs = {
    'DanKuGa_Azteca': '0x00',
    'DanKuGa_Barts': '0x01',
    'DanKuGa_Boggy': '0x02',
    'DanKuGa_Gekkou': '0x03',
    'DanKuGa_Gonzales': '0x04',
    'DanKuGa_JMcCoy': '0x05',
    'DanKuGa_Kazuya': '0x06',
    'DanKuGa_Lihua': '0x07',
    'DanKuGa_Liza': '0x08',
    'DanKuGa_Marco': '0x09',
    'DanKuGa_Wulong': '0x0A',
    'DanKuGa_Bonus': '0x0B',
    'DanKuGa_General': '0x0C',

    'LandMaker_Common': '0x0D',
    'LandMaker_Intro': '0x0E',
    'LandMaker_Stages': '0x0F',
    'LandMaker_Aifa': '0x10',
    'LandMaker_Gaira': '0x11',
    'LandMaker_Hiryu': '0x12',
    'LandMaker_Kouko': '0x13',
    'LandMaker_Ranju': '0x14',
    'LandMaker_Renki': '0x15',
    'LandMaker_Rinrei': '0x16',
    'LandMaker_Roushinshi': '0x17',
    'LandMaker_Soumei': '0x18',
    'LandMaker_Youen': '0x19'
}
DanKuGa_imgIDs = {
    'Base': '0x00',
    'SelectPortrait': '0x40',
    'WinPortrait': '0x41',
}
DanKuGa_CharSpec_imgIDs = {
    'DanKuGa_Azteca': {  # unitID: 0x00
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_Barts': {  # unitID: 0x01
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_Boggy': {  # unitID: 0x02
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_Gekkou': {  # unitID: 0x03
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_Gonzales': {  # unitID: 0x04
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_JMcCoy': {  # unitID: 0x05
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_Kazuya': {  # unitID: 0x06
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_Lihua': {  # unitID: 0x07
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_Liza': {  # unitID: 0x08
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_Marco': {  # unitID: 0x09
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_Wulong': {  # unitID: 0x0A
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
    'DanKuGa_Bonus': {  # unitID: 0x0B
        'Names_Barts': '0x00',
        'Names_Kazuya': '0x01',
    },
    'DanKuGa_General': {  # unitID: 0x0C
        'Base': '0x00',
        'SelectPortrait': '0x40',
        'WinPortrait': '0x41',
    },
}

LandMaker_CharSpec_imgIDs = {
    'LandMaker_Common': {
        'Tiles_Base': '0x0',
        'Tiles_ColorSpread': '0x1',
        'Tiles_ColorShine': '0x2',
        'Map_Buildings': '0x40',
    },
    'LandMaker_Intro': {
    },
    'LandMaker_Stages': {
        'Hiryu_Case': '0x0',
        'Hiryu_Grid': '0x1',
        'Aifa_Case': '0x2',
        'Aifa_Grid': '0x3',
        'Soumei_Case': '0x4',
        'Soumei_Grid': '0x5',
        'Renki_Case': '0x6',
        'Renki_Grid': '0x7',
        'Youen_Case': '0x8',
        'Youen_Grid': '0x9',
        'Kouko_Case': '0xa',
        'Kouko_Grid': '0xb',
        'Rinrei_Case': '0xc',
        'Rinrei_Grid': '0xd',
        'Roushinshi_Case': '0xe',
        'Roushinshi_Grid': '0xf',
        'Ranju_Case': '0x10',
        'Ranju_Grid': '0x11',
        'Gaira_Case': '0x12',
        'Gaira_Grid': '0x13',
    },
    'LandMaker_Aifa': {
        'Buildings': '0x00',
        'Chibi': '0x01',
        'Efx_1': '0x02',
        'Efx_2': '0x03',
        'Efx_3': '0x04',
        'Efx_4': '0x05',
        'Efx_5': '0x06',
        'Burned': '0x08',
        'Frozen': '0x09',
        'MudDamage': '0x0a',
        'Zapped': '0x0b',
        'SelectPortrait': '0x20',
        'SelectIcon': '0x21',
        'WinPortrait': '0x22',
        'WinBackground': '0x23',
        'AttackPortrait1': '0x24',
        'AttackPortrait2': '0x25',
        'AttackPortrait3': '0x26',
    },
    'LandMaker_Gaira': {
        'Buildings': '0x00',
        'Chibi': '0x01',
        'Efx_1': '0x02',
        'Efx_2': '0x03',
        'Efx_3': '0x04',
        'Efx_4': '0x05',
        'Efx_5': '0x06',
        'Efx_6': '0x07',
        'Burned': '0x08',
        'Frozen': '0x09',
        'SelectPortrait': '0x20',
        'SelectIcon': '0x21',
        'WinPortrait': '0x22',
        'WinBackground': '0x23',
        'AttackPortrait1': '0x24',
        'AttackPortrait2': '0x25',
        'AttackPortrait3': '0x26',
    },
    'LandMaker_Hiryu': {
        'Buildings': '0x00',
        'Chibi': '0x01',
        'Efx_1': '0x02',
        'Efx_2': '0x03',
        'Efx_3': '0x04',
        'Efx_4': '0x05',
        'Efx_5': '0x06',
        'Burned': '0x08',
        'Frozen': '0x09',
        'SelectPortrait': '0x20',
        'SelectIcon': '0x21',
        'WinPortrait': '0x22',
        'WinBackground': '0x23',
        'AttackPortrait1': '0x24',
        'AttackPortrait2': '0x25',
        'AttackPortrait3': '0x26',
        'Buildings_HiryuSoumei': '0x40',
    },
    'LandMaker_Kouko': {
        'Buildings': '0x00',
        'Chibi': '0x01',
        'Efx_1': '0x02',
        'Efx_2': '0x03',
        'Efx_3': '0x04',
        'Efx_4': '0x05',
        'Efx_5': '0x06',
        'Burned': '0x08',
        'Frozen': '0x09',
        'SelectPortrait': '0x20',
        'SelectIcon': '0x21',
        'WinPortrait': '0x22',
        'WinBackground': '0x23',
        'AttackPortrait1': '0x24',
        'AttackPortrait2': '0x25',
        'AttackPortrait3': '0x26',
    },
    'LandMaker_Ranju': {
        'Buildings': '0x00',
        'Chibi': '0x01',
        'Efx_1': '0x02',
        'Efx_2': '0x03',
        'Efx_3': '0x04',
        'Efx_4': '0x05',
        'Efx_5': '0x06',
        'Efx_6': '0x07',
        'Frozen': '0x09',
        'Zapped': '0x0b',
        'Efx_7': '0x0f',
        'SelectPortrait': '0x20',
        'SelectIcon': '0x21',
        'WinPortrait': '0x22',
        'WinBackground': '0x23',
        'AttackPortrait1': '0x24',
        'AttackPortrait2': '0x25',
        'AttackPortrait3': '0x26',
        'PSAttackPortrait1': '0x27',
        'PSAttackPortrait2': '0x28',
        'PSAttackPortrait3': '0x29',
    },
    'LandMaker_Renki': {
        'Buildings': '0x00',
        'Chibi': '0x01',
        'Efx_1': '0x02',
        'Efx_2': '0x03',
        'Efx_3': '0x04',
        'Efx_4': '0x05',
        'Efx_5': '0x06',
        'Efx_6': '0x07',
        'Burned': '0x08',
        'Frozen': '0x09',
        'MudDamage': '0x0a',
        'Infatuated': '0x0c',
        'SelectPortrait': '0x20',
        'SelectIcon': '0x21',
        'WinPortrait': '0x22',
        'WinBackground': '0x23',
        'AttackPortrait1': '0x24',
        'AttackPortrait2': '0x25',
        'AttackPortrait3': '0x26',
    },
    'LandMaker_Rinrei': {
        'Buildings': '0x00',
        'Chibi': '0x01',
        'Efx_1': '0x02',
        'Efx_2': '0x03',
        'Efx_3': '0x04',
        'Efx_4': '0x05',
        'Efx_5': '0x06',
        'Burned': '0x08',
        'Frozen': '0x09',
        'SelectPortrait': '0x20',
        'SelectIcon': '0x21',
        'WinPortrait': '0x22',
        'WinBackground': '0x23',
        'AttackPortrait1': '0x24',
        'AttackPortrait2': '0x25',
        'AttackPortrait3': '0x26',
    },
    'LandMaker_Roushinshi': {
        'Buildings': '0x00',
        'Chibi': '0x01',
        'Efx_1': '0x02',
        'Efx_2': '0x03',
        'Efx_3': '0x04',
        'Efx_4': '0x05',
        'Efx_5': '0x06',
        'Efx_6': '0x07',
        'Burned': '0x08',
        'Frozen': '0x09',
        'MudDamage': '0x0a',
        'Efx_7': '0x0f',
        'SelectPortrait': '0x20',
        'SelectIcon': '0x21',
        'WinPortrait_Roushinshi': '0x22',
        'WinBackground': '0x23',
        'AttackPortrait1': '0x24',
        'AttackPortrait2': '0x25',
        'AttackPortrait3': '0x26',
        'WinPortrait_Shaoren': '0x27',
    },
    'LandMaker_Soumei': {
        'Buildings': '0x00',
        'Chibi': '0x01',
        'Efx_1': '0x02',
        'Efx_2': '0x03',
        'Efx_3': '0x04',
        'Efx_4': '0x05',
        'Efx_5': '0x06',
        'Burned': '0x08',
        'Frozen': '0x09',
        'MudDamage': '0x0a',
        'Zapped': '0x0b',
        'Efx_7': '0x0f',
        'SelectPortrait': '0x20',
        'SelectIcon': '0x21',
        'WinPortrait': '0x22',
        'WinBackground': '0x23',
        'AttackPortrait1': '0x24',
        'AttackPortrait2': '0x25',
        'AttackPortrait3': '0x26',
    },
    'LandMaker_Youen': {
        'Buildings': '0x00',
        'Chibi': '0x01',
        'Efx_1': '0x02',
        'Efx_2': '0x03',
        'Efx_3': '0x04',
        'Efx_5': '0x06',
        'Burned': '0x08',
        'Frozen': '0x09',
        'MudDamage': '0x0a',
        'SelectPortrait': '0x20',
        'SelectIcon': '0x21',
        'WinPortrait': '0x22',
        'WinBackground': '0x23',
        'AttackPortrait1': '0x24',
        'AttackPortrait2': '0x25',
        'AttackPortrait3': '0x26',
    },
}

# ======================================================================================================================
# NEOGEO                                                                                     +
# ======================================================================================================================
# NEOGEO-unit-0x00-imgid-0x00-
NEOGEO_unitIDs = {
    # NeoBomberman
    'NeoBomberman_AtomicBomber': '0x00',
    'NeoBomberman_Baketama': '0x01',
    'NeoBomberman_Bomberman': '0x02',
    'NeoBomberman_CatBomber': '0x03',
    'NeoBomberman_Charge': '0x04',
    'NeoBomberman_Dachon': '0x05',
    'NeoBomberman_Dokyuun': '0x06',
    'NeoBomberman_FakeBomber': '0x07',
    'NeoBomberman_Gaikottsu': '0x08',
    'NeoBomberman_GoldenBomber': '0x09',
    'NeoBomberman_HayateBomber': '0x0A',
    'NeoBomberman_Honey': '0x0B',
    'NeoBomberman_Kotetsu': '0x0C',
    'NeoBomberman_MrBird': '0x0D',
    'NeoBomberman_Nucha': '0x0E',
    'NeoBomberman_Onbu': '0x0F',
    'NeoBomberman_RidgeRazor': '0x10',
    'NeoBomberman_RubberBomber': '0x11',
    'NeoBomberman_Tamagon': '0x12',
    'NeoBomberman_Bonus': '0x13',

# NinjaMasters 0x14-0x21
# DDragon 0x22-0x2E
# RotD 0x2F-0x3F
# KotM 0x40-0x46
# SavReign 0x47-0x52

    'MagDrop3_BlkPierrot': '0x53',
    'MagDrop3_Chariot': '0x54',
    'MagDrop3_Death': '0x55',
    'MagDrop3_Devil': '0x56',
    'MagDrop3_Emperor': '0x57',
    'MagDrop3_Empress': '0x58',
    'MagDrop3_Fool': '0x59',
    'MagDrop3_Fortune': '0x5A',
    'MagDrop3_HangedMan': '0x5B',
    'MagDrop3_Hermit': '0x5C',
    'MagDrop3_Hierophant': '0x5D',
    'MagDrop3_HighPriestess': '0x5E',
    'MagDrop3_Judgement': '0x5F',
    'MagDrop3_Justice': '0x60',
    'MagDrop3_Lovers': '0x61',
    'MagDrop3_Magician': '0x62',
    'MagDrop3_Moon': '0x63',
    'MagDrop3_Star': '0x64',
    'MagDrop3_Strength': '0x65',
    'MagDrop3_StrFather': '0x66',
    'MagDrop3_Sun': '0x67',
    'MagDrop3_Temperance': '0x68',
    'MagDrop3_Tower': '0x69',
    'MagDrop3_World': '0x6A',
    'MagDrop3_Bonus': '0x6B',

# SDB 0x6C-0x7A
# VFG 0x7B-0x88
# GalaxyFight 0x89-0x96
# KabukiKlash 0x97-0xA5
# KizunaE 0xA6-0xB1
# AoDK 0xB2-0xBB

    'MagDrop2_BlkPierrot': '0xBC',
    'MagDrop2_Chariot': '0xBD',
    'MagDrop2_Devil': '0xBE',
    'MagDrop2_Empress': '0xBF',
    'MagDrop2_Fool': '0xC0',
    'MagDrop2_HighPriestess': '0xC1',
    'MagDrop2_Justice': '0xC2',
    'MagDrop2_Magician': '0xC3',
    'MagDrop2_Star': '0xC4',
    'MagDrop2_Strength': '0xC5',
    'MagDrop2_World': '0xC6',
    'MagDrop2_Bonus': '0xC7',

# Flipshot 0xC8-0xCE
}

NEOGEO_imgIDs = {
    'Base': '0x00',
}
NEOGEO_CharSpec_imgIDs = {
    'NeoBomberman_AtomicBomber': {  # unit: 0x00
        'Base': '0x00',
    },
    'NeoBomberman_Kotetsu': {
        'Base': '0x00',
        'SkullEffect': '0x01',
    },

    'MagDrop3_BlkPierrot': {  # unitID: 0x53
        'Base': '0x00',
        'Map': '0x38',
    },
    'MagDrop3_Chariot': {  # unitID: 0x54
        'Base': '0x00',
        'Map': '0x38',
        'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Death': {  # unitID: 0x55
        'Base': '0x00',
        'LosingFlash': '0x01',
        'Map': '0x38',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Devil': {  # unitID: 0x56
        'Base': '0x00',
        'Map': '0x38',
        'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Emperor': {  # unitID: 0x57
        'Base': '0x00',
        'Map': '0x38',
        'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Empress': {  # unitID: 0x58
        'Base': '0x00',
        'WinExtra': '0x01',
        'Map': '0x38',
        'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Fool': {  # unitID: 0x59
        'Base': '0x00',
        'Map': '0x38',
        'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Fortune': {  # unitID: 0x5A
        'Base': '0x00',
        'Wheel': '0x01', # ???
        'Map': '0x38',
    },
    'MagDrop3_HangedMan': {  # unitID: 0x5B
        'Base': '0x00',
        'Map': '0x38',
        'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Hermit': {  # unitID: 0x5C
        'Base': '0x00',
        'LosingFlash': '0x01',
        'Map': '0x38',
        'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Hierophant': {  # unitID: 0x5D
        'Base': '0x00',
        'Map': '0x38',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_HighPriestess': {  # unitID: 0x5E
        'Base': '0x00',
        'VerA_Base': '0x01',
        'VerB_Base': '0x02',

        'Map': '0x38',
        'VerA_Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Judgement': {  # unitID: 0x5F
        'Base': '0x00',
        'Map': '0x38',
        'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Justice': {  # unitID: 0x60
        'Base': '0x00',
        'Map': '0x38',
        'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Lovers': {  # unitID: 0x61
        'Base': '0x00',
        'Map': '0x38',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Magician': {  # unitID: 0x62
        'Base': '0x00',
        'Map': '0x38',
        'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Moon': {  # unitID: 0x63
        'Base': '0x00',
        'Map': '0x38',
        # 'Portrait': '0x40',
        'PreFightIcon': '0x41',
    },
    'MagDrop3_Star': {  # unitID: 0x64
        'Base': '0x00',
        'VerA_Base': '0x01',
        'VerB_Base': '0x02',
        'Map': '0x38',
        'VerA_PreFightIcon': '0x41',

    },
    'MagDrop3_Strength': {  # unitID: 0x65
        'Base': '0x00',
        'Map': '0x38',
    },
    'MagDrop3_StrFather': {  # unitID: 0x66
        'Base': '0x00',
        'Map': '0x38',
    },
    'MagDrop3_Sun': {  # unitID: 0x67
        'Base': '0x00',
        'VerA_Base': '0x01',
        'VerB_Base': '0x02',
        'Map': '0x38',
        # 'VerA_Portrait': '0x40',
        # 'PreFightIcon': '0x41',
        'VerB_Portrait': '0x42',

    },
    'MagDrop3_Temperance': {  # unitID: 0x68
        'Base': '0x00',
        'Map': '0x38',
    },
    'MagDrop3_Tower': {  # unitID: 0x69
        'Base': '0x00',
        'Map': '0x38',
        'Portrait': '0x40',
    },
    'MagDrop3_World': {  # unitID: 0x6A
        'Base': '0x00',
        'VerA_Base': '0x01',
        'VerB_Base': '0x02',
        'Map': '0x38',
        'VerA_Portrait': '0x40',
    },
    'MagDrop3_Bonus': {  # unitID: 0x6B
        'SelectIcons01': '0x01',
        'SelectIcons02': '0x02',
        'SelectIcons03': '0x03',
        'SelectIcons04': '0x04',
        'SelectIcons05': '0x05',
        'SelectIcons06': '0x06',
        'SelectIcons07': '0x07',
        'SelectIcons08': '0x08',
        'SelectIcons09': '0x09',
        'SelectIcons10': '0x10',
        'SelectScreen_DataEastLogo': '0x11',
        'SelectScreen_MainBackground': '0x12',
        'SelectScreen_PortraitBackground': '0x13',
    },

    'MagDrop2_BlkPierrot': {  # unitID: 0xBC
        'Base': '0x00',
    },
    'MagDrop2_Chariot': {  # unitID: 0xBD
        'Base': '0x00',
        'Icon': '0x08',
    },
    'MagDrop2_Devil': {  # unitID: 0xBE
        'Base': '0x00',
    },
    'MagDrop2_Empress': {  # unitID: 0xBF
        'Base': '0x00',
        'Icon': '0x08',
    },
    'MagDrop2_Fool': {  # unitID: 0xC0
        'Base': '0x00',
        'Icon': '0x08',
    },
    'MagDrop2_HighPriestess': {  # unitID: 0xC1
        'Base': '0x00',
        'Icon': '0x08',
    },
    'MagDrop2_Justice': {  # unitID: 0xC2
        'Base': '0x00',
        'Icon': '0x08',
    },
    'MagDrop2_Magician': {  # unitID: 0xC3
        'Base': '0x00',
        'Icon': '0x08',
    },
    'MagDrop2_Star': {  # unitID: 0xC4
        'Base': '0x00',
    },
    'MagDrop2_Strength': {  # unitID: 0xC5
        'Base': '0x00',
    },
    'MagDrop2_World': {  # unitID: 0xC6
        'Base': '0x00',
        'Icon': '0x08',
    },
    'MagDrop2_Bonus': {  # unitID: 0xC7
    },

}